---
application:
  name: "groupmusicbot"
  project: "ub"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "daisy"
  version: "4.4"
routers:
- name: "main-groupmusicbot"
  routes:
  - application_name: "groupmusicbot"
    paths:
    - "/*"
